application: streamspigot
version: 2
runtime: python
api_version: 1

builtins:
- appstats: on
- remote_api: on
- datastore_admin: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /googled756c8e5e6bbce3a.html
  static_files: static/googled756c8e5e6bbce3a.html
  upload: static/googled756c8e5e6bbce3a.html

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(cron|tasks)/.*
  script: cron_tasks.py
  login: admin

- url: /_ereporter.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: main.py

